name: Release

on:
  release:
    types:
      - published

jobs:
  release:
      name: Release
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.18'
        - name: Update module index
          run: curl "https://proxy.golang.org/github.com/kumpmati/go-tasuku/@v/$(git describe HEAD --tags --abbrev=0).info"
